### PR TITLE
add some shitty 8ball outcomes

### PR DESCRIPTION
**Pull request by DuneEryksson**
yeet

two are from https://en.wikipedia.org/wiki/Magic_8-Ball#Possible_answers if you can't read comments

### CODE REVIEW

**Comment by DuneEryksson** [comment]
image
you fucking what

**Comment by DuneEryksson** [comment]
image
goddamnit

**Comment by DuneEryksson** [comment]
smooth sailing from here FeelsGoodMan

**Comment by suvanl** [comment]
All checks have passed now, will merge 👍

**Pull request merged**
